### ISSUE TITLE
Context output support

### ISSUE THREAD

**Issue by nicka** [ACloudGuru/api-gateway-policy-gen#1]
The output can also include a context map containing key-value pairs. The following shows an example of this output.

```json
{
  "principalId": "",
  "policyDocument": {},
  "context": {
    "stringKey": "value",
    "numberKey": 1,
    "booleanKey": true
  }
}
```

**Comment by nicka** [comment]
Woah you are fast 🎉

**Comment by johncmckim** [comment]
Haha. It's a nice easy change. Didn't know the `context` feature existed. I can see good uses for it.

Let me know if there's any issues with it.

**Comment by nicka** [comment]
Was testing with this today, works pretty good actually 👍
